name: Docker Compose CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docker-compose-ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and run containers
      run: |
        docker compose up -d --build

    - name: Wait for containers to be healthy
      run: sleep 10

    - name: Check running containers
      run: docker ps

    - name: Stop containers
      run: docker compose down
